### ISSUE TITLE
Null point error occured when a column exists next map type column

### ISSUE THREAD

**Issue by mosasiru** [toyama0919/embulk-input-presto#3]
This is my presto Schema.

```
 CREATE TABLE hoge (
    user_id bigint,
    data map(varchar, varchar)
 )
```

and this is my config.

```
in:
  type: presto
  host: -
  catalog: -
  schema:  -
  query: SELECT data, user_id FROM hoge LIMIT 100
out:
  type: stdout
```

This occurs null pointer error.

More details,

OK `SELECT user_id, data FROM hoge LIMIT 100` 
OK `SELECT user_id FROM hoge LIMIT 100` 
OK `SELECT data FROM hoge LIMIT 100` 
NG `SELECT data, user_id FROM hoge LIMIT 100`

So, null point error occured when a column exists next map type column.

error message is below.

```
2017-02-16 07:56:44.026 +0000: Embulk v0.8.16
2017-02-16 07:56:47.673 +0000 [INFO] (0001:transaction): Loaded plugin embulk-input-presto (0.2.4)
org.embulk.exec.PartialExecutionException: org.jruby.exceptions.RaiseException: (RuntimeError) Unknown type nil
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:373)
	at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:591)
	at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:389)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:385)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
	at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:385)
	at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
	at RUBY.run(/usr/local/bin/embulk!/embulk/runner.rb:84)
	at RUBY.run(/usr/local/bin/embulk!/embulk/command/embulk_run.rb:307)
	at RUBY.<main>(/usr/local/bin/embulk!/embulk/command/embulk_main.rb:2)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
	at usr.local.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(usr/local/bin/embulk/embulk/command/file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at usr.local.bin.embulk.embulk.command.embulk_bundle.<main>(file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
	at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
	at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
	at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
	at org.jruby.Main.internalRun(org/jruby/Main.java:313)
	at org.jruby.Main.run(org/jruby/Main.java:242)
	at org.jruby.Main.main(org/jruby/Main.java:204)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
	Suppressed: java.lang.NullPointerException
		at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:494)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:425)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:421)
		at org.embulk.spi.Exec.doWith(Exec.java:25)
		at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:421)
		at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:184)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:453)
		at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:314)
		at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:46)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
		at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)
		at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
		at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
		at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
		at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
		at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
		at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
		at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
		at org.jruby.Ruby.runInterpreter(Ruby.java:850)
		at org.jruby.Ruby.loadFile(Ruby.java:2976)
		at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:243)
		at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
		at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:885)
		at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:525)
		at org.jruby.runtime.load.LoadService.require(LoadService.java:396)
		at org.jruby.RubyKernel.requireCommon(RubyKernel.java:963)
		at org.jruby.RubyKernel.require19(RubyKernel.java:956)
		at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
		at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:383)
		at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
		at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
		at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
		at usr.local.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51)
		at usr.local.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51)
		at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
		at org.jruby.ir.Compiler$1.load(Compiler.java:111)
		at org.jruby.Ruby.runScript(Ruby.java:834)
		at org.jruby.Ruby.runNormally(Ruby.java:749)
		at org.jruby.Ruby.runNormally(Ruby.java:767)
		at org.jruby.Ruby.runFromMain(Ruby.java:580)
		at org.jruby.Main.doRunFromMain(Main.java:425)
		at org.jruby.Main.internalRun(Main.java:313)
		at org.jruby.Main.run(Main.java:242)
		at org.jruby.Main.main(Main.java:204)
		at org.embulk.cli.Main.main(Main.java:23)
Caused by: org.jruby.exceptions.RaiseException: (RuntimeError) Unknown type nil
	at RUBY.block in initialize(/usr/local/bin/embulk!/embulk/schema.rb:41)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1734)
	at RUBY.initialize(/usr/local/bin/embulk!/embulk/schema.rb:20)
	at RUBY.block in transaction(/usr/local/bin/embulk!/embulk/input_plugin.rb:56)
	at RUBY.resume(/home/hoge/.embulk/jruby/2.3.0/gems/embulk-input-presto-0.2.4/lib/embulk/input/presto.rb:35)
	at RUBY.transaction(/home/hoge/.embulk/jruby/2.3.0/gems/embulk-input-presto-0.2.4/lib/embulk/input/presto.rb:31)
	at RUBY.transaction(/usr/local/bin/embulk!/embulk/input_plugin.rb:54)
	at RUBY.run(/usr/local/bin/embulk!/embulk/runner.rb:84)
	at RUBY.run(/usr/local/bin/embulk!/embulk/command/embulk_run.rb:307)
	at RUBY.<main>(/usr/local/bin/embulk!/embulk/command/embulk_main.rb:2)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
	at usr.local.bin.embulk.embulk.command.embulk_bundle.<main>(file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51)

Error: org.jruby.exceptions.RaiseException: (RuntimeError) Unknown type nil
```

**Comment by y-matsuwitter** [comment]
This maybe caused by below line with the schema contains `map` type.
https://github.com/toyama0919/embulk-input-presto/blob/c1afe1edea4af93eb8eafed18fe73bbbb45dff9b/lib/embulk/input/presto/explain_parser.rb#L9

Presto's explain query shows the map type column like `data:map(varchar, varchar)`. 

Example: 

```
- Output[data, user_id] => [data:map(varchar, varchar), user_id:bigint]
    - Project => [data:map(varchar, varchar), user_id:bigint]
        - Limit[100] => [user_id:bigint, data:map(varchar, varchar)]
            - RemoteExchange[GATHER] => user_id:bigint, data:map(varchar, varchar)
                - LimitPartial[100] => [user_id:bigint, data:map(varchar, varchar)]
                    - TableScan[hive:hive:default:hoge, originalConstraint = true] => [user_id:bigint, data:map(varchar, varchar)]
                            LAYOUT: hive
                            user_id := HiveColumnHandle{clientId=hive, name=user_id, hiveType=bigint, hiveColumnIndex=0, columnType=REGULAR}
                            data := HiveColumnHandle{clientId=hive, name=data, hiveType=map<string,string>, hiveColumnIndex=12, columnType=REGULAR}
                            HiveColumnHandle{clientId=hive, name=dt, hiveType=string, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                                :: [[2016120217, 2017021608]]
```

But the format this plugin expects is `data:map`. 

In this case, specifying column types in configuration may helps.

**Comment by mosasiru** [comment]
we found out that adding`columns` option works good although this is deprecated.

```
- type
   - name: data
     type: json
   - name: user_id
     type: long
```

**Comment by toyama0919** [comment]
Thanks for bug report.
reviewing PR..

**Comment by toyama0919** [comment]
released.

embulk-input-presto | RubyGems.org | your community gem host https://rubygems.org/gems/embulk-input-presto/versions/0.2.5
